# fly.toml app configuration file generated for young-snow-2852 on 2023-11-11T00:24:43+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "young-snow-2852"
primary_region = "arn"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
